[tool.poetry]
name = "echo-app-poetry"
version = "0.1.0"
description = ""
authors = ["r8vnhill <reachme@ravenhill.cl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
